.PHONY: all clean tests
CC=g++
CFLAGS=-Wall -Wextra -std=c++17 -march=native -O2
CLINK=-c

all: main

main: main.o parser.o
	$(CC) $(CFLAGS) main.o parser.o -o main

parser.o: parser.cpp
	$(CC) $(CFLAGS) $(CLINK) parser.cpp -o parser.o

main.o: main.cpp
	$(CC) $(CFLAGS) $(CLINK) main.cpp -o main.o
	
clean:
	rm -f parser.o main.o
	
test: parser.o
	$(CC) $(CFLAGS) test1.cpp parser.o -o test1
	./test1 > output.txt
	if diff output.txt outtest1.txt >> /dev/null ; then echo "Test 1 succed\n" ; else echo "Test 1 failed\n" ; fi
	
	$(CC) $(CFLAGS) test2.cpp parser.o -o test2
	./test2 > output.txt
	if diff output.txt outtest2.txt >> /dev/null ; then echo "Test 2 succed\n" ; else echo "Test 2 failed\n" ; fi
	
	$(CC) $(CFLAGS) test3.cpp parser.o -o test3
	./test3 > output.txt
	if diff output.txt outtest3.txt >> /dev/null ; then echo "Test 3 succed\n" ; else echo "Test 3 failed\n" ; fi
	
	rm -f test1 test2 test3 output.txt
